name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: arthiondaena/SQLchat
        huggingface_repo_id: Invicto69/SQLchat
        repo_type: space
        space_sdk: streamlit
        private: false
        hf_token: ${{ secrets.HF_TOKEN }}